apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: j4p62bwd5-java-quarkus 
  janus-idp.io/tekton: j4p62bwd5-java-quarkus
  backstage.io/kubernetes-id: j4p62bwd5-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: j4p62bwd5-java-quarkus
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml